---
version: "3"

tasks:
  build:
    desc: Run mkdocs build command
    silent: true
    cmds:
      - .venv/bin/mkdocs build

  serve:
    desc: Run mkdocs serve command
    silent: true
    cmds:
      - .venv/bin/mkdocs serve

  serve-doc-test:
    desc: Run mkdocs serve command on doc test
    silent: true
    cmds:
      - .venv/bin/mkdocs serve --dev-addr localhost:8001 --config-file tests/fixtures/test_doc/mkdocs.yml
