---
version: "3"

vars:
  PYTHON_MIN_VERSION: 3.9
  TASK_MIN_VERSION: 3.45.4
  ASCIINEMA_PLAYER_VERSION: 3.11.1

includes:
  check: .taskfiles/check.yml
  lint: .taskfiles/lint.yml
  test: .taskfiles/test.yml
  update: .taskfiles/update.yml
  mkdocs: .taskfiles/mkdocs.yml

tasks:
  default:
    cmds:
      - task: help

  bootstrap:
    desc: Bootstrap project
    deps: [check:all]
    silent: true
    cmds:
      - poetry install

  clean:
    desc: Cleanup project
    silent: true
    cmds:
      - poetry env remove --all
      - rm -rf .mypy_cache
      - rm -rf .pytest_cache
      - rm -rf .ruff_cache
      - rm -rf .task
      - rm -rf build
      - rm -rf dist
      - rm -rf site
      - rm -rf src/mkdocs_asciinema_player.egg-info
      - rm -rf src/mkdocs_asciinema_player/__pycache__
      - rm -rf tests/unit/__pycache__
      - rm -rf core

  reinit:
    desc: Reinit project
    silent: true
    cmds:
      - task: clean
      - task: bootstrap

  pipeline:
    desc: Simulate run pipeline
    silent: true
    cmds:
      - task: lint:all
      - task: test:pytest

  help:
    desc: Display help
    silent: true
    cmds:
      - task --list
