---
version: "3"

dotenv: [".config/environments/.env"]

vars:
  PYTHON: '{{.PYTHON | default "python3"}}'
  PYTHON_MIN_VERSION: 3.9
  TASK_MIN_VERSION: 3.39.2
  ASCIINEMA_PLAYER_VERSION: 3.8.1

includes:
  check: .taskfiles/check.yml
  lint: .taskfiles/lint.yml
  test: .taskfiles/test.yml
  update: .taskfiles/update.yml
  mkdocs: .taskfiles/mkdocs.yml

tasks:
  default:
    cmds:
      - task: help

  bootstrap:
    desc: Bootstrap Python venv (requirements)
    deps: [check:all]
    silent: true
    cmds:
      - |
        {{.PYTHON}} -m venv .venv
        .venv/bin/pip install --upgrade pip build twine
        .venv/bin/pip install -e .[dev,lint,test]

  clean:
    desc: Cleanup project
    silent: true
    cmds:
      - rm -rf .mypy_cache
      - rm -rf .pytest_cache
      - rm -rf .task
      - rm -rf .venv
      - rm -rf build
      - rm -rf dist
      - rm -rf docs/assets/css
      - rm -rf docs/assets/js
      - rm -rf site
      - rm -rf src/mkdocs_asciinema_player.egg-info
      - rm -rf src/mkdocs_asciinema_player/__pycache__
      - rm -rf tests/unit/__pycache__

  reinit:
    desc: Reinitialization Python venv (requirements)
    silent: true
    cmds:
      - task: clean
      - task: bootstrap

  pipeline:
    desc: Simulate run pipeline
    silent: true
    cmds:
      - task: lint:all
      - task: test:pytest

  help:
    desc: Display help
    silent: true
    cmds:
      - task --list
