---
version: "3"

env:
  UV_LINK_MODE: copy

includes:
  lint: .taskfiles/lint.yml
  test: .taskfiles/test.yml
  update: .taskfiles/update.yml
  mkdocs: .taskfiles/mkdocs.yml

tasks:
  default:
    cmds:
      - task --list

  clean:
    desc: Cleanup project
    silent: true
    cmds:
      - rm -rf .venv

  lint:
    desc: Run linters
    silent: true
    cmds:
      - task: lint:all

  test:
    desc: Run tests
    silent: true
    cmds:
      - for: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        task: test:pytest
        vars:
          PYTHON_VERSION: "{{.ITEM}}"

  pipeline:
    desc: Simulate run pipeline
    silent: true
    cmds:
      - task: lint
      - task: test
